### ISSUE TITLE
Unable to build in latest Inform 7 release 6L38

### ISSUE THREAD

**Issue by frankhale** [jmacdotorg/warblers-nest#1]
I was trying to build the source in the latest version of Inform 7 (6L38) and I came across some problems that I am unsure of how to fix. If you have any idea and can offer some help that would be awesome. Here is a listing of the errors reported by Inform:

In Chapter 0 - Setup:

Problem. You wrote 'Before of praying while in the graves'  , which seems to introduce a rule taking effect only 'while in the graves'. But this condition did not make sense, so I am unable to accept this rule.

 See the manual: 7.12 > 7.12. In the presence of, and when

---

Problem. You wrote 'Instead of singing during Crisis'  , which seems to introduce a rule taking effect only if the action is 'singing'. But that did not make sense as a description of an action. I am unable to place this rule into any rulebook.

 See the manual: 7.1 > 7.1. Actions

---

Problem. You wrote 'Instead of singing'  , which seems to introduce a rule taking effect only if the action is 'singing'. But that did not make sense as a description of an action. I am unable to place this rule into any rulebook.

---

In Chapter 1 - The Reeds, Section 1 - Regions and backdrops:

Problem. You wrote 'Instead of entering the cottage while in the graves'  , which seems to introduce a rule taking effect only 'while in the graves'. But this condition did not make sense, so I am unable to accept this rule.

---

In Section 3 - The reeds:

Problem. In 'After entering the MIddleReeds while the invisible bird is in the MiddleReeds for the first time'  , I'm not able to understand what specific thing is meant by the phrase 'the invisible bird'. You use the definite article 'the', which suggests you have a particular thing in mind, but then you go on to refer to a kind rather than something definite. Quite likely a human reading this sentence would find it obvious what you mean, but I don't. 

 This often arises when writing something like: 'Instead of opening a door when the door is closed' - where clearly a human would understand that 'the door' refers to the same one in 'a door' earlier. I can make sense of this only if you help: for example, 'Instead of opening a door (called the portal) when the portal is closed' would work. So would 'Instead of opening a closed door'; or 'Instead of opening a door which is closed'. All of these alternatives help me by making clear that only one door is being talked about.

---

Problem. You wrote 'Instead of listening while in the reed banks'  , which seems to introduce a rule taking effect only 'while in the reed banks'. But this condition did not make sense, so I am unable to accept this rule.

---

In Section 4 - The Beach:

Problem. You wrote 'Instead of inserting the river into two eggshells'  , which seems to introduce a rule taking effect only if the action is 'inserting the river into two eggshells'. But that did not make sense as a description of an action. I am unable to place this rule into any rulebook.

---

Problem. You wrote 'Instead of entering the reeds while in the beach'  , which seems to introduce a rule taking effect only 'while in the beach'. But this condition did not make sense, so I am unable to accept this rule.

---

In Chapter 2 - The Garden:

Problem. You wrote 'Instead of entering the reed backdrop while in outdoors'  , which seems to introduce a rule taking effect only 'while in outdoors'. But this condition did not make sense, so I am unable to accept this rule.

---

In Section 1 - Listening to stuff in the garden:

Problem. You wrote 'Instead of listening while in the garden'  , which seems to introduce a rule taking effect only 'while in the garden'. But this condition did not make sense, so I am unable to accept this rule.

---

In Chapter 3 - Inside the cottage, Section The baby-feeling state machine:

Problem. You wrote 'Before doing anything in indoors'  , which seems to introduce a rule taking effect only if the action is 'doing anything in indoors'. But that did not make sense as a description of an action. I am unable to place this rule into any rulebook.

```
```

**Comment by jmacdotorg** [comment]
Howdy! Thanks for taking this code for a spin on the latest Inform.

I frankly have nothing immediately to suggest, since (other than tinkering for the sake of the IFComp) I haven't worked with last year's major release of Inform 7, and do not have a feel for the various peculiarities it introduced. I'd last had reason to compile  _Warbler's Nest_ in 2013, with 6G60 (which should continue to compile this source with no errors).

As I cannot predict when I'd have the opportunity to examine and fix this code for 6L38's sake, I would invite you to have a go at it yourself, if you'd like to. Pull requests quite welcome...!

**Comment by frankhale** [comment]
Okay if I'm able to solve these I'll submit a pull request.

**Comment by frankhale** [comment]
Okay I spent some time on this but I don't think I'm going to be able to solve the issues. Fixing one issue leads to a Pandora's box of more compilation errors. Inform is complaining on stuff that doesn't look like it should be a problem. I'm supposing there were syntax changes, rule definition changes in the latest version. The documentation isn't leading me in any meaningful way to proper resolutions. I'm going to close this for now.

**Comment by jmacdotorg** [comment]
I appreciate the effort anyway!

I'll update the repository's README with an appropriate admonition / invitation. Thanks again for letting me know about this.

**Comment by juhana** [comment]
Almost all of those have the same issue: old versions of Inform accepted `when in (room)` as a shorthand for `when the player is in (room)` but in the latest you have to type the whole thing. There might be other issues that those errors shadow but making that one change should get you far. 

I can make a pull request with the fixes sometime soon-ish unless someone else beats me to it.

(This probably shouldn't be closed for as long as the issue remains.)

**Comment by frankhale** [comment]
I'll try that when I get home. I must have been way off the deep end last
night because the stuff I was trying was leading to even more errors.

**Comment by jmacdotorg** [comment]
(Re-opening because, as Juhana points out, this actually is an issue that needs fixin', one way or another.)

**Comment by frankhale** [comment]
Okay cool. I'm going to try out the suggested fix now.

**Comment by juhana** [comment]
As for the first three errors, the problem there is that singing and praying actions used to be provided by the Standard Rules but they have now been removed. They'll need to be re-implemented or copy-pasted from the old Standard Rules.

 Not sure what's wrong with "inserting the river into two eggshells." This is just a guess but possibly the word "two" confuses the compiler, so it might help to rename the object into "two-eggshells" and then saying `The printed name of two-eggshells is "two eggshells".`

**Comment by jmacdotorg** [comment]
I just committed some fixes from myself and @vaughany. @frankhale, could you pull the latest changes and see if the game works better now?

**Comment by frankhale** [comment]
Awesome! I will try it out tomorrow.

**Comment by frankhale** [comment]
Okay, I've compiled it in Inform 7 and everything is great. The game is running. Thank you so much for looking into this!

**Comment by jmacdotorg** [comment]
Thanks for reporting it!
